### ISSUE TITLE
RMF fleet adapter does not read level_name from /fleet_states messages

### ISSUE THREAD

**Issue by webvenky** [open-rmf/rmf#135]
- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  - Docker
- OpenRMF version or commit hash
  - Latest ( I used `docker pull ghcr.io/open-rmf/rmf/rmf_demos:latest` )

I use `free_fleet_server_ros2` node to publish the `/fleet_states`. It looks like below:
```
---
name: hospi_robot
robots:
- name: hospi_robot_0
  model: robot_model
  task_id: ''
  seq: 0
  mode:
    mode: 0
    mode_request_id: 0
  battery_percent: 99.0
  location:
    t:
      sec: 13
      nanosec: 396000000
    x: 58.44990158081055
    y: -184.5000762939453
    yaw: -2.351127862930298
    level_name: B1
    index: 0
  path: []
---
```

But I get this message from the full_control fleet adapter, when I run the simulation:
```
[full_control-1] [ERROR] [1643943567.067598981] [hospi_robot_fleet_adapter]: Unable to compute a StartSet for robot [hospi_robot_0] using level_name [] and location [58.449944, -184.500015, -2.350461] specified in its RobotState message. This can happen if the level_name in the RobotState message does not match any of the map names in the navigation graph supplied or if the location reported in the RobotState message is far way from the navigation graph. This robot will not be added to the fleet [hospi_robot]. The following hint may help with debugging: None of the waypoints in the graph are on a map called [].
```
I checked the nav_graph/0.yaml and it has `B1` level. The fleet adapter is able to get the `robot_name` and `pose: x,y,yaw` information correctly though.

Do I need to publish any other details on the `fleet_states` message?
