### ISSUE TITLE
[Other issue]: Invalid Data in /fleet_states Topic for Real Robot with use_sim_time Set to False

### ISSUE THREAD

**Issue by osama-z-salah** [open-rmf/rmf#551]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I am using a real robot (nano500xw02) with use_sim_time set to false, and I am experiencing an issue with the values published in the /fleet_states topic. When I monitor the topic using ros2 topic echo /fleet_states, the values appear unrealistic, specifically:

Battery Percentage: 1.401298464324817e-45
Location (x, y, yaw):
x: 7.507128761641381e+23
y: 0.00036577426362782717
yaw: 7.976202964782715
Here is a sample output from the /fleet_states topic:

```
nanofleet@nanofleet:~/nrmf_ws$ ros2 topic echo /fleet_states 
name: Robot500xw
robots:
- name: nano500xw02
  model: Robot500xw
  task_id: compose.dispatch-106
  seq: 0
  mode:
    mode: 0
    mode_request_id: 0
  battery_percent: 1.401298464324817e-45
  location:
    t:
      sec: 0
      nanosec: 1105939276
    x: 7.507128761641381e+23
    y: 0.00036577426362782717
    yaw: 7.976202964782715
    obey_approach_speed_limit: true
    approach_speed_limit: -1.5556764602661133
    level_name: ''
    index: 54202487275523
  path: []

```

API Endpoint Data: Interestingly, when I query the data using the RMF API fleet endpoint, I receive correct and realistic values for the same robot:

```
[
  {
    "name": "Robot500xw",
    "robots": {
      "nano500xw02": {
        "name": "nano500xw02",
        "status": "working",
        "task_id": "Chargeb459d6",
        "unix_millis_time": 1730083331990,
        "location": {
          "map": "L1",
          "x": 9.743598937988281,
          "y": -5.146598815917969,
          "yaw": 1.56088125705719
        },
        "battery": 0.2906574462890625,
        "issues": [],
        "commission": {
          "dispatch_tasks": true,
          "direct_tasks": true,
          "idle_behavior": true
        },
        "mutex_groups": {
          "locked": [],
          "requesting": []
        }
      }
    }
  }
]
```
